name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check style with flake8
      run: |
        flake8 . --show-source --statistics
    - name: Run pytest with coverage
      run: |
        pytest --cov=app --cov-report=term-missing
    - name: Check coverage
      run: |
        coverage report --fail-under=100